---
# tasks file for nginx

- name: Install nginx
  yum: name=nginx state=present
  become: true

- name: Copy nginx configuration for wordpress
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
  become: true

- name: insert firewalld rule for nginx
  firewalld: port={{ nginx_port }}/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes
  become: true

- name: http service state
  service: name=nginx state=started enabled=yes
  become: true
