---
# tasks file for helloworld

- name: Download WordPress
  get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/srv/wordpress-{{ wp_version }}.tar.gz
           sha256sum="{{ wp_sha256sum }}"
  become: yes

- name: Extract archive
  command: chdir=/srv/ /bin/tar xvf wordpress-{{ wp_version }}.tar.gz creates=/srv/wordpress
  become: yes

- name: Add group "wordpress"
  group: name=wordpress
  become: yes

- name: Add user "wordpress"
  user: name=wordpress group=wordpress home=/srv/helloworld/
  become: yes

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  become: no

- name: Create WordPress database
  mysql_db: name={{ wp_db_name }} state=present
  become: yes

- name: Create WordPress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present
  become: yes

- name: Copy WordPress config file
  template: src=wp-config.php dest=/srv/helloworld/
  become: yes

- name: Change ownership of WordPress installation
  file: path=/srv/helloworld/ owner=wordpress group=wordpress state=directory recurse=yes
  become: yes

- name: install SEManage
  yum: pkg=policycoreutils-python state=present
  become: yes

- name: set the SELinux policy for the Wordpress directory
  command: semanage fcontext -a -t httpd_sys_content_t "/srv/wordpress(/.*)?"
  become: yes

- name: set the SELinux policy for wp-config.php
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/helloworld/wp-config\.php"
  become: yes

- name: set the SELinux policy for wp-content directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/helloworld/wp-content(/.*)?"
  become: yes

- name: set the SELinux policy for the *.php files
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/helloworld/.*\.php"
  become: yes

- name: set the SELinux policy for the Upgrade directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/helloworld/wp-content/upgrade(/.*)?"
  become: yes

- name: set the SELinux policy for the Uploads directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/helloworld/wp-content/uploads(/.*)?"
  become: yes

- name: set the SELinux policy for the wp-includes php files
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/helloworld/wp-includes/.*\.php"
  become: yes

- name: set the SELinux on all the Files
  command: restorecon -Rv /srv/helloworld
  become: yes

#- name: Start php-fpm Service
#  service: name=php-fpm state=started enabled=yes
#  become: yes
